name: Setup Spread Sheets

inputs:
  release-spreadsheet-id:
    description: Release Note Spread Sheets ID
    required: true
  member-spreadsheet-id:
    description: Member Spread Sheets ID
    required: true
  slack-post-url:
    description: Post URL
    required: true
  pr-contents:
    description: JSON PR contents
    required: false
  workload-identity-provider:
    required: true
  service-account:
    required: true
  enable-overwrite:
    required: false
    default: true
  sheet-name:
    required: false
    default: シート1

runs:
  using: composite

  steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache-dependency-path: package-lock.json

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-

    - name: Install modules
      shell: bash
      run: |-
        cd "${GITHUB_ACTION_PATH}"
        npm ci

    - name: build
      shell: bash
      run: |-
        # build
        cd "${GITHUB_ACTION_PATH}"
        ls "${GITHUB_ACTION_PATH}"/../../../
        echo "----------------------"
        if [ ! -e "${GITHUB_ACTION_PATH}"/../../../pr_jarray.json ]; then
          echo '[{"id":"ii123iiei3t","type":"Chores","scope":"UNDEFINED","title":"update sheet","labels":"ci","url":"https://github.com/autowarefoundation/autoware.universe/pull/1","author":"poke", "approver":"tkimura4\nTakaHoeibe","description":"REMOVE THE WORLD","related_links":"UNDEFINED","test_performed":"UNDEFINED","note_for_reviewers":"UNDEFINED"}]' > "${GITHUB_ACTION_PATH}"/../../../pr_jarray.json
        fi
        ls "${GITHUB_ACTION_PATH}"/../../../
        npx tsc

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}

    - name: gcloud auth login by workload identity
      shell: bash
      run: |-
        # gcloud auth login
        cd "${GITHUB_ACTION_PATH}"
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

    - name: Update spread sheet
      shell: bash
      run: |-
        # update spread sheet
        cd "${GITHUB_ACTION_PATH}"
        tree ../../../ -L 3
        node dist/work/setup-spread-sheets/setup-spread-sheets/src/pr_index.js
      env:
        RELEASE_SPREADSHEET_ID: ${{ inputs.release-spreadsheet-id }}
        MEMBER_SPREADSHEET_ID: ${{ inputs.member-spreadsheet-id }}
        SLACK_POST_URL: ${{ inputs.slack-post-url }}
        PR_CONTENTS: ${{ inputs.pr-contents }}
        ENABLE_OVERWRITE: ${{ inputs.enable-overwrite }}
        SHEET_NAME: ${{ inputs.sheet-name }}
