name: test-generate-release-note
on:
  push:
  workflow_dispatch:

jobs:
  oidc:
    environment: oidc

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          release-spreadsheet-id: ${{ secrets.RELEASE_SPREADSHEET_ID }}
          member-spreadsheet-id: ${{ secrets.MEMBER_SPREADSHEET_ID }}
          slack-post-url: ${{ secrets.SLACK_POST_URL }}
          pr-contents: '[{"id":"ii123iiei3t","type":"Chores","scope":"UNDEFINED","title":"update sheet","labels":"ci","url":"https://github.com/autowarefoundation/autoware.universe/pull/1","author":"tkimura4", "approver":"shmpwk","description":"UNDEFINED","related_links":"UNDEFINED","test_performed":"UNDEFINED","note_for_reviewers":"hoge"}]'
          workload-identity-provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ secrets.SERVICE_ACCOUNT }}
