name: test-generate-release-note
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [feat/repository-dispatch]

jobs:
  write-sheet-post-slack:
    environment: oidc

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - if: github.event.client_payload
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - uses: ./
        with:
          release-spreadsheet-id: ${{ secrets.RELEASE_SPREADSHEET_ID }}
          member-spreadsheet-id: ${{ secrets.MEMBER_SPREADSHEET_ID }}
          slack-post-url: ${{ secrets.SLACK_POST_URL }}
          pr-contents: '[{"id":"ii123iiei3t","type":"Chores","scope":"UNDEFINED","title":"update sheet","labels":"ci","url":"https://github.com/autowarefoundation/autoware.universe/pull/1","author":"poke", "approver":"tkimura4\nTakaHoeibe","description":"REMOVE THE WORLD","related_links":"UNDEFINED","test_performed":"UNDEFINED","note_for_reviewers":"UNDEFINED"}]'
          workload-identity-provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ secrets.SERVICE_ACCOUNT }}
          sheet-name: "sheet1"
          file-id: '1GTiAXvEhsTsr_UBxcwNcaoetETXzQrSD'
