name: test-generate-release-note
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [feat/repository-dispatch]

jobs:
  write-sheet-post-slack:
    environment: oidc

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - if: github.event.client_payload
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Event Information
        run: |
          echo "hoge"
